-- ============================================================
-- Execute no SQL Editor do Supabase
-- Apaga os serviços antigos e insere a lista completa
-- ============================================================

-- Limpa serviços existentes para evitar duplicatas
DELETE FROM services;

-- Insere TODOS os 20 serviços completos
INSERT INTO services (category, name, "desc", price, time) VALUES

-- Studio Lorena
('lorena', 'Axila',            'Remoção com cera de alta qualidade.',                         20,  15),
('lorena', 'Virilha completa', 'Depilação íntima com máximo conforto e discrição.',            50,  35),
('lorena', 'Perna inteira',    'Depilação completa das pernas.',                               50,  45),
('lorena', 'Meia perna',       'Depilação parcial da perna.',                                  30,  25),
('lorena', 'Rosto',            'Remoção de pelos faciais com cera suave.',                     20,  20),
('lorena', 'Buço',             'Limpeza rápida e eficaz.',                                     10,  10),
('lorena', 'Braço inteiro',    'Depilação completa dos braços.',                               20,  25),
('lorena', 'Costas',           'Depilação feminina das costas.',                               20,  25),
('lorena', 'Sobrancelha',      'Design e limpeza de sobrancelhas.',                            15,  15),

-- Barber Lounge Márcio
('marcio', 'Barba',                  'Cuidado masculino para a barba com toalha quente.',      20,  30),
('marcio', 'Corte',                  'Corte de cabelo masculino e infantil.',                   20,  40),
('marcio', 'Pelos do nariz e orelha','Remoção indolor e precisa.',                             20,  15),
('marcio', 'Depilação costas',       'Depilação com cera especial masculina.',                  20,  25),
('marcio', 'Depilação peito',        'Depilação com cera especial masculina.',                  20,  25),
('marcio', 'Perna inteira',          'Depilação completa das pernas.',                          50,  45),
('marcio', 'Parte íntima',           'Depilação com total discrição e higiene.',                50,  45),
('marcio', 'Combo depilação total',  'Pacote completo: corpo total ou parcial.',               150, 120),
('marcio', 'Matizador para Barba',   'Realce a cor da sua barba.',                             10,  15),
('marcio', 'Mechas no Cabelo',       'Estilo moderno e iluminado.',                            50,  60),
('marcio', 'Desenhos Freestyle',     'Arte exclusiva em cortes.',                              30,  30);

-- Confirma quantos foram inseridos (deve retornar 20)
SELECT category, name, price, time FROM services ORDER BY category, id;

-- ============================================================
-- Estrutura para Galeria e Comentários (Nova funcionalidade)
-- ============================================================

-- Tabela de Galeria (se já existir, adiciona as colunas)
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS description TEXT;

-- Tabela de Comentários da Galeria (Usa UUID para alinhar com o ID da galeria)
CREATE TABLE IF NOT EXISTS gallery_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id UUID REFERENCES gallery(id) ON DELETE CASCADE,
    username TEXT NOT NULL,
    comment TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- Estrutura para Ambientes (Cards Destaque na Home)
-- ============================================================

CREATE TABLE IF NOT EXISTS environments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subtitle TEXT NOT NULL,
    title TEXT NOT NULL,
    image_url TEXT NOT NULL,
    "order" INTEGER DEFAULT 0
);

-- Insere os 3 ambientes padrão caso a tabela esteja vazia
INSERT INTO environments (subtitle, title, image_url, "order")
SELECT 'Barber Lounge', 'A Cadeira de Márcio', 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&q=80&w=600', 1
WHERE NOT EXISTS (SELECT 1 FROM environments WHERE "order" = 1);

INSERT INTO environments (subtitle, title, image_url, "order")
SELECT 'Cabines Estéticas', 'Refúgio Lorena', 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&q=80&w=600', 2
WHERE NOT EXISTS (SELECT 1 FROM environments WHERE "order" = 2);

INSERT INTO environments (subtitle, title, image_url, "order")
SELECT 'Bem-Vindo', 'Atendimento Single Malt', 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&q=80&w=600', 3
WHERE NOT EXISTS (SELECT 1 FROM environments WHERE "order" = 3);

-- Tabela de Configurações Gerais do Site
CREATE TABLE IF NOT EXISTS site_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- Insere imagem da capa padrão caso não exista
INSERT INTO site_settings (key, value) 
VALUES ('hero_image', 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&q=80&w=600') 
ON CONFLICT (key) DO NOTHING;

-- Suporte a Vídeos na Galeria
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'image';
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS video_url TEXT;

-- ============================================================
-- Nossa Equipe (gerenciável pelo painel admin)
-- ============================================================

CREATE TABLE IF NOT EXISTS team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    bio TEXT NOT NULL,
    icon TEXT DEFAULT 'fa-user',
    highlights JSONB DEFAULT '[]'::jsonb,
    image_url TEXT,
    "order" INTEGER DEFAULT 0,
    visible BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

INSERT INTO team_members (name, role, bio, icon, highlights, "order", visible)
SELECT 'Lorena', 'Estética & Depilação Avançada',
    'Especializada em técnicas francesas de depilação orgânica, Lorena transformou a depilação tradicional em um ritual de bem-estar. Utilizando ceras de ativos botânicos desenvolvidas artesanalmente para peles sensíveis, ela foca no alívio de dor, na hidratação pós-remoção e na privacidade absoluta de cada cliente, seja feminina ou geral.',
    'fa-leaf',
    '["Depilação com Cera Orgânica Calmante","Tratamentos de Foliculite de alta performance","Design de Sobrancelhas de Visagismo"]'::jsonb,
    1, true
WHERE NOT EXISTS (SELECT 1 FROM team_members WHERE name = 'Lorena');

INSERT INTO team_members (name, role, bio, icon, highlights, "order", visible)
SELECT 'Márcio', 'Barbeiro & Corporal Masculino',
    'Márcio combina a navalha clássica italiana e as tesouras de alta precisão com o que há de mais moderno em estética de pelos masculinos. Além de barbas terapêuticas esculpidas à toalha quente, ele é pioneiro em depilação masculina integral e corporal com técnicas que reduzem drasticamente o desconforto e garantem um visual limpo e polido.',
    'fa-scissors',
    '["Barboterapia com Toalhas Quentes e Óleos Essenciais","Cortes Clássicos e Contemporâneos","Depilação Corporal Masculina (total discrição)"]'::jsonb,
    2, true
WHERE NOT EXISTS (SELECT 1 FROM team_members WHERE name = 'Márcio');

INSERT INTO team_members (name, role, bio, icon, highlights, "order", visible)
SELECT 'Giovanna', 'Administração, Reparo de Equipamentos e Esterilização',
    'Giovanna garante a excelência nos bastidores do atelier. Especialista na manutenção técnica dos equipamentos de ponta, também supervisiona rigorosamente a esterilização de grau médico, oferecendo o mais alto padrão de higiene e gestão do ambiente.',
    'fa-clipboard-check',
    '["Gestão Administrativa","Reparo de Equipamentos","Esterilização de Instrumentais"]'::jsonb,
    3, true
WHERE NOT EXISTS (SELECT 1 FROM team_members WHERE name = 'Giovanna');

INSERT INTO site_settings (key, value) VALUES ('team_section_label', 'Nossa Equipe') ON CONFLICT (key) DO NOTHING;
INSERT INTO site_settings (key, value) VALUES ('team_section_title', 'Mãos esculpidas na tradição do cuidado sob medida') ON CONFLICT (key) DO NOTHING;
